name: CI build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    container:
      image: espressif/idf:v5.5.1
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ESP-IDF environment
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          idf.py --version

      - name: Build project
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          idf.py set-target esp32c6
          idf.py build
